version: "3"

services:

  fastapi-auth:
    container_name: fastapi-auth
    build:
        context: .
        dockerfile: ./fastapi_service/Dockerfile
    environment:
      - DAGSHUB_USER=${DAGSHUB_USER}
      - DAGSHUB_PASSWORD=${DAGSHUB_PASSWORD}
      - DAGSHUB_TOKEN=${DAGSHUB_TOKEN}
      - DAGSHUB_URI=${DAGSHUB_URI}
      - DAGSHUB_NAME_MODEL=${DAGSHUB_NAME_MODEL}
      - DAGSHUB_VERSION_MODEL=${DAGSHUB_VERSION_MODEL}
      - FASTAPI_DB_HOST=${FASTAPI_DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${FASTAPI_DB_HOST}
      - FASTAPI_DB_PORT=${FASTAPI_DB_PORT}
      - FASTAPI_PG_DB=${FASTAPI_PG_DB}
      - AWS_ACCESS_READ_KEY_ID=${AWS_ACCESS_READ_KEY_ID}
      - AWS_SECRET_ACCESS_READ_KEY=${AWS_SECRET_ACCESS_READ_KEY}
      - AWS_ACCESS_WRITE_KEY_ID=${AWS_ACCESS_WRITE_KEY_ID}
      - AWS_SECRET_ACCESS_WRITE_KEY=${AWS_SECRET_ACCESS_WRITE_KEY}
      - BUCKET_ID=${BUCKET_ID}
    ports:
      - 80:80
