"""add create items

Revision ID: c73e547724ea
Revises: 75fcce75298e
Create Date: 2025-01-15 21:52:11.195558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c73e547724ea'
down_revision: Union[str, None] = '75fcce75298e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('s3_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_items_s3_path'), 'items', ['s3_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_s3_path'), table_name='items')
    op.drop_column('items', 's3_path')
    # ### end Alembic commands ###
