"""complate without test (add predict)

Revision ID: f3bb1f2d021c
Revises: 4885f68cdcae
Create Date: 2025-01-20 01:17:05.225520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3bb1f2d021c'
down_revision: Union[str, None] = '4885f68cdcae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
