"""add CASCADE delet for user delete

Revision ID: 75fcce75298e
Revises: b4c629472db8
Create Date: 2025-01-15 20:36:34.570443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75fcce75298e'
down_revision: Union[str, None] = 'b4c629472db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_owner_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tokens_user_id_fkey', 'tokens', type_='foreignkey')
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.create_foreign_key('tokens_user_id_fkey', 'tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_owner_id_fkey', 'items', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
