"""fix create_item post, add access_token

Revision ID: 9216c2da6a2b
Revises: c73e547724ea
Create Date: 2025-01-15 21:58:52.871655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9216c2da6a2b'
down_revision: Union[str, None] = 'c73e547724ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
