"""add uuid with create user

Revision ID: b4c629472db8
Revises: 808c4abb67f6
Create Date: 2025-01-15 20:21:24.999422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c629472db8'
down_revision: Union[str, None] = '808c4abb67f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('s3_folder_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_s3_folder_id'), 'users', ['s3_folder_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_s3_folder_id'), table_name='users')
    op.drop_column('users', 's3_folder_id')
    # ### end Alembic commands ###
